"""Add srcImg and price columns

Revision ID: bd1ba812b678
Revises: 
Create Date: 2024-11-21 17:17:09.373886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1ba812b678'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadium', schema=None) as batch_op:
        batch_op.add_column(sa.Column('srcImg', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadium', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('srcImg')

    # ### end Alembic commands ###
